<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxPELO8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxPELO8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRxPELO8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRxPELO8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRxPELO8\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'RxPELO8',
    'container.build_id' => 'd8b43cbb',
    'container.build_time' => 1548407454,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxPELO8');
